# Generated by Django 3.2.8 on 2021-11-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_id', models.IntegerField()),
                ('Employee_Name', models.CharField(max_length=100)),
                ('Employee_Salary', models.IntegerField()),
                ('Employee_Address', models.CharField(max_length=225)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Date_Time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
