# Generated by Django 3.2.8 on 2021-11-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('idd', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
            ],
        ),
    ]
