# Generated by Django 3.2.9 on 2021-11-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAdminModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('username', models.CharField(max_length=25)),
                ('isexicuted', models.CharField(default='False', editable=False, max_length=10)),
            ],
        ),
    ]
